name: ppml
channels:
  - anaconda
dependencies:
  - ipykernel=6.25.1
  - ipython=8.14.0
  - jupyter=1.0.0
  - jupyterlab=4.0.5
  - matplotlib=3.7.2
  - notebook=7.0.2
  - numpy=1.25.2
  - pandas=2.0.3
  - pillow=9.4.0
  - pip=23.2.1
  - python=3.11
  - pytorch=2.0.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - setuptools=68.0.0
  - torchvision=0.15.2
  - tqdm=4.66.1
  - pip:
      - flwr[simulation]==1.4.0
      - opacus==1.4.0
      - phe==1.5.0