name: ppml
dependencies:
  - ipykernel>=6.19
  - ipython>=8.12
  - jupyter=1.0.0
  - jupyterlab>=3.6
  - matplotlib>=3.7
  - notebook>=6.5.4
  - numpy>=1.24
  - pandas>=1.5
  - pillow>=9.4
  - pip>=23.1
  - python=3.10
  - pytorch::pytorch>=1.13
  - scikit-learn>=1.2
  - scipy>=1.10
  - setuptools>=67.8.0
  - pytorch::torchvision>=0.14.1
  - tqdm>=4.65.0
  - grpcio>=1.48,<1.52
  - pip:
      - opacus>=1.4
      - pydantic>=1.10
      - flwr[simulation]==1.4.0
      - notexbook-theme==2.0.1
      - phe==1.5.0
