name: ppml
channels:
  - pytorch
  - conda-forge
dependencies:
  - ipython>=7.34.0
  - jupyter>=1.0.0
  - matplotlib>=3.5.1
  - notebook>=6.4.10
  - numpy>=1.21.2
  - opacus=1.1.1
  - pandas>=1.3.5
  - pip>=22.0.4
  - python>=3.9.12
  - pytorch==1.9.0
  - scikit-learn>=1.0.2
  - scipy>=1.7.3
  - setuptools>=62.0.0
  - torchvision==0.9.1
  - tqdm>=4.64.0
  - pip:
      - jinja2==3.1.1
      - notexbook-theme>=2.0.1
      - phe==1.4.0
      - syft==0.5.1
